In [7]:
import numpy as np
import LinConGauss as lcg

In [44]:
# shiftvals = np.random.rand(5, 1)
shiftvals = np.array([[1, 2, 5, 8, 9]])
# shiftvals = np.array([[.16, .56, .85, .83, .87]])

In [45]:
x_init = np.array([1,2])

A = np.array([[1,2,3], [4,5,6]])
b = np.array([1,1,1])

lincon = lcg.LinearConstraints(A, b)

In [46]:
sn = lcg.multilevel_splitting.SubsetNesting(lincon, .5)

In [47]:
sn._update_fix_shift(10, shiftvals)

array([0, 0, 0, 0, 0])

In [48]:
sn._update_find_shift(shiftvals)

ValueError: kth(=5) out of bounds (5)

In [25]:
X = np.array([[-4,1,2], [3,2,3], [-1, -1, 1]])

shiftvals = -np.amin(lincon.evaluate(X), axis = 0)

In [31]:
idx = np.argpartition(shiftvals, 1)[:3]

In [33]:
idx[:-1]

array([2, 1])

In [49]:
shiftvals

array([[1, 2, 5, 8, 9]])

In [56]:
np.int(np.array([132, 2]))

TypeError: only size-1 arrays can be converted to Python scalars

In [64]:
print(A)
np.amin(A, 0)

[[1 2 3]
 [4 5 6]]


array([1, 2, 3])